mysql:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  database: ${MySQL_DATABASE}
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
aliyun-oss:
  endpoint: ${ALIYUN_OSS_ENDPOINT}
  access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
  access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
  bucket-name: ${ALIYUN_OSS_BUCKET_NAME}
