spring:
  application:
    name: springboot-blog
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${mysql.username}
    password: ${mysql.password}
  
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      
mybatis-plus:
#  mapper-locations: classpath*:org/example/springbootblog/mapper/*.xml
#  type-aliases-package: org.example.springbootblog.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
aliyun:
  oss:
    endpoint: ${aliyun-oss.endpoint}
    access-key-id: ${aliyun-oss.access-key-id}
    access-key-secret: ${aliyun-oss.access-key-secret}
    bucket-name: ${aliyun-oss.bucket-name}